name: mygoat
description: "A professional offline-first goat farm management app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  path_provider: ^2.1.5
  flutter_riverpod: ^2.5.1
  supabase_flutter: ^2.14.1
  connectivity_plus: ^6.1.1 # Lowered slightly to fit your target SDK floor safely
  image_picker: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  isar_generator: 3.1.0+1 # Fixes the version mismatch error entirely